-- NeKoRoSHELL modern Hyprland configuration
-- Hyprland 0.55+ / Lua configuration
-- No external desktop-framework dependency.

local HOME = os.getenv("HOME")
local NKS = HOME .. "/.local/bin/nekoroshell"
local function run(cmd) hl.exec_cmd(cmd) end

local function wallust_color(name, fallback)
    local path = HOME .. "/.cache/wallust/colors-hyprland.conf"
    local f = io.open(path, "r")
    if not f then
        return fallback
    end
    local value
    for line in f:lines() do
        local n, v = line:match("^%s*%$([%w_]+)%s*=%s*(%S+)")
        if n == name then
            value = v
            break
        end
    end
    f:close()
    return value or fallback
end

local active_border = wallust_color("color13", "rgb(8BD5FF)")
local inactive_border = wallust_color("inactive", "rgba(51,54,61,0.65)")

-- Environment ---------------------------------------------------------------
hl.env("PATH", NKS .. ":" .. HOME .. "/.local/bin:" .. HOME .. "/.cargo/bin:" .. (os.getenv("PATH") or ""))
hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("QT_QPA_PLATFORM", "wayland;xcb")
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")
hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", "1")
hl.env("MOZ_ENABLE_WAYLAND", "1")
hl.env("GDK_BACKEND", "wayland,x11,*")
hl.env("SDL_VIDEODRIVER", "wayland")
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "wayland")

-- Machine-specific graphics configuration is generated by the installer.
-- It is intentionally separate so the same NKS tree works on Intel, AMD,
-- NVIDIA, and hybrid systems without hard-coding one vendor into the base config.
local hardware_lua = HOME .. "/.config/hypr/hardware.lua"
local hardware_file = io.open(hardware_lua, "r")
if hardware_file then
    hardware_file:close()
    dofile(hardware_lua)
end

-- Monitor fallback. Hyprland applies this to displays not otherwise matched.
hl.monitor({
    output = "",
    mode = "preferred",
    position = "auto",
    scale = 1,
})

-- Core appearance -----------------------------------------------------------
hl.config({
    general = {
        gaps_in = 5,
        gaps_out = 20,
        border_size = 2,
        col = {
            active_border = active_border,
            inactive_border = inactive_border,
        },
        resize_on_border = false,
        allow_tearing = false,
        layout = "dwindle",
    },

    decoration = {
        rounding = 10,
        rounding_power = 2,
        active_opacity = 0.94,
        inactive_opacity = 0.72,
        shadow = {
            enabled = true,
            range = 4,
            render_power = 3,
            color = "rgb(000000)",
        },
        blur = {
            enabled = true,
            size = 5,
            passes = 2,
            vibrancy = 0.1696,
        },
    },

    dwindle = {
        preserve_split = true,
        smart_split = true,
        smart_resizing = true,
    },

    misc = {
        disable_hyprland_logo = true,
        force_default_wallpaper = 0,
        disable_splash_rendering = true,
        initial_workspace_tracking = 1,
        on_focus_under_fullscreen = 1,
        allow_session_lock_restore = true,
    },

    input = {
        kb_layout = "us",
        follow_mouse = 1,
        sensitivity = 0,
        touchpad = {
            natural_scroll = false,
        },
    },

    xwayland = {
        force_zero_scaling = true,
    },
})

-- Animations ----------------------------------------------------------------
hl.config({
    animations = {
        enabled = true,
        bezier = {
            "wind, 0.05, 0.9, 0.1, 1.05",
            "winIn, 0.1, 1.1, 0.1, 1.1",
            "winOut, 0.3, -0.3, 0, 1",
            "liner, 1, 1, 1, 1",
            "almostLinear, 0.5, 0.5, 0.75, 1.0",
        },
        animation = {
            "windows, 1, 6, wind, slide",
            "windowsIn, 1, 6, winIn, slide",
            "windowsOut, 1, 5, winOut, slide",
            "windowsMove, 1, 5, wind, slide",
            "border, 1, 1, liner",
            "borderangle, 1, 30, liner, loop",
            "layers, 1, 6, wind, popin 90%",
            "layersIn, 1, 6, winIn, popin 90%",
            "layersOut, 1, 5, winOut, popin 90%",
            "workspaces, 1, 5, wind",
            "fadeIn, 1, 1.73, almostLinear",
            "fadeOut, 1, 1.46, almostLinear",
            "fade, 1, 3.03, almostLinear",
        },
    },
})

-- Window rules --------------------------------------------------------------
hl.window_rule({
    name = "nks-suppress-maximize",
    match = { class = ".*" },
    suppress_event = "maximize",
})

hl.window_rule({
    name = "nks-fix-xwayland-drags",
    match = {
        class = "^$",
        title = "^$",
        xwayland = true,
        float = true,
        fullscreen = false,
        pin = false,
    },
    no_focus = true,
})

hl.window_rule({
    name = "nks-dashboard",
    match = { class = "^(fastfetch-grid|clock-grid|cava-grid|btop-grid)$" },
    float = true,
    opacity = 0.6,
})

hl.window_rule({
    name = "nks-pip",
    match = { title = "^([Pp]icture[- ]?[Ii]n[- ]?[Pp]icture)$" },
    float = true,
    pin = true,
    focus_on_activate = false,
    no_initial_focus = true,
    suppress_event = "activate",
})

hl.workspace_rule({
    workspace = "1",
    layout = "dwindle",
})

-- Keybindings ----------------------------------------------------------------
-- Keep letter keysyms lowercase to match the current Hyprland Lua API.
-- Modifier names remain uppercase (SUPER, SHIFT, CTRL, ALT).
local M = "SUPER"
local function bind(key, dispatcher, description, flags)
    flags = flags or {}
    flags.description = description
    hl.bind(key, dispatcher, flags)
end

-- Workspaces: SUPER+1..0 focuses, SUPER+SHIFT+1..0 moves the active window.
for i = 1, 10 do
    local key = (i == 10) and "0" or tostring(i)
    bind(M .. " + " .. key, hl.dsp.focus({ workspace = tostring(i) }), "Focus workspace " .. i)
    bind(M .. " + SHIFT + " .. key, hl.dsp.window.move({ workspace = tostring(i) }), "Move window to workspace " .. i)
end

-- Focus navigation: arrows and the standard H/J/K/L vim-style layout.
bind(M .. " + left",  hl.dsp.focus({ direction = "l" }), "Focus left")
bind(M .. " + right", hl.dsp.focus({ direction = "r" }), "Focus right")
bind(M .. " + up",    hl.dsp.focus({ direction = "u" }), "Focus up")
bind(M .. " + down",  hl.dsp.focus({ direction = "d" }), "Focus down")
bind(M .. " + h",     hl.dsp.focus({ direction = "l" }), "Focus left (H)")
bind(M .. " + l",     hl.dsp.focus({ direction = "r" }), "Focus right (L)")
bind(M .. " + k",     hl.dsp.focus({ direction = "u" }), "Focus up (K)")
bind(M .. " + j",     hl.dsp.focus({ direction = "d" }), "Focus down (J)")

-- Mouse / workspace navigation.
bind(M .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }), "Next workspace")
bind(M .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }), "Previous workspace")
bind(M .. " + mouse:272", hl.dsp.window.drag(), "Move window with mouse", { mouse = true })
bind(M .. " + mouse:273", hl.dsp.window.resize(), "Resize window with mouse", { mouse = true })

-- Applications.
bind(M .. " + RETURN", hl.dsp.exec_cmd("setsid -f kitty >/dev/null 2>&1"), "Open terminal")
bind(M .. " + e", hl.dsp.exec_cmd("nks-open-file-manager"), "Open a new Nautilus window")
bind(M .. " + ALT + m", hl.dsp.exec_cmd("setsid -f nwg-displays >/dev/null 2>&1"), "Configure displays")
bind(M .. " + ALT + n", hl.dsp.exec_cmd("setsid -f gnome-text-editor >/dev/null 2>&1"), "Open text editor")
bind(M .. " + CTRL + RETURN", hl.dsp.exec_cmd("setsid -f rofi-launch drun >/dev/null 2>&1"), "Open application launcher")
bind(M .. " + ALT + c", hl.dsp.exec_cmd("setsid -f rofi-launch run >/dev/null 2>&1"), "Run a command")
bind(M .. " + SHIFT + c", hl.dsp.exec_cmd("setsid -f rofi-launch game >/dev/null 2>&1"), "Open game launcher")

-- Window actions.
bind(M .. " + q", hl.dsp.window.close(), "Close active window")
bind(M .. " + SHIFT + q", hl.dsp.window.kill(), "Kill active window")
bind(M .. " + f", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }), "Toggle fullscreen")
bind(M .. " + m", hl.dsp.window.fullscreen({ mode = "maximized", action = "toggle" }), "Toggle maximize")
bind(M .. " + t", hl.dsp.window.float({ action = "toggle" }), "Toggle floating")
bind(M .. " + ALT + t", function()
    hl.dispatch(hl.dsp.window.float({ action = "toggle" }))
    hl.dispatch(hl.dsp.window.pin({ action = "toggle" }))
end, "Toggle floating and pinned")
bind(M .. " + SHIFT + j", hl.dsp.layout("togglesplit"), "Toggle split direction")
bind(M .. " + p", hl.dsp.window.pseudo(), "Toggle pseudo")

-- Resize and swap.
bind(M .. " + SHIFT + right", hl.dsp.window.resize({ x = 100, y = 0, relative = true }), "Increase window width", { repeating = true })
bind(M .. " + SHIFT + left", hl.dsp.window.resize({ x = -100, y = 0, relative = true }), "Decrease window width", { repeating = true })
bind(M .. " + SHIFT + down", hl.dsp.window.resize({ x = 0, y = 100, relative = true }), "Increase window height", { repeating = true })
bind(M .. " + SHIFT + up", hl.dsp.window.resize({ x = 0, y = -100, relative = true }), "Decrease window height", { repeating = true })
bind(M .. " + ALT + left", hl.dsp.window.swap({ direction = "l" }), "Swap window left")
bind(M .. " + ALT + right", hl.dsp.window.swap({ direction = "r" }), "Swap window right")
bind(M .. " + ALT + up", hl.dsp.window.swap({ direction = "u" }), "Swap window up")
bind(M .. " + ALT + down", hl.dsp.window.swap({ direction = "d" }), "Swap window down")

-- NKS actions.
bind(M .. " + CTRL + r", hl.dsp.exec_cmd("hyprctl reload"), "Reload Hyprland")
bind(M .. " + PRINT", hl.dsp.exec_cmd("screenshot output"), "Screenshot output")
bind(M .. " + ALT + f", hl.dsp.exec_cmd("screenshot output"), "Screenshot output")
bind(M .. " + ALT + s", hl.dsp.exec_cmd("screenshot region"), "Screenshot region")
bind(M .. " + CTRL + k", hl.dsp.exec_cmd("setsid -f show-keybinds >/dev/null 2>&1"), "Show keybindings")
bind(M .. " + v", hl.dsp.exec_cmd("cliphist list | rofi -dmenu | cliphist decode | wl-copy"), "Clipboard manager")
bind(M .. " + CTRL + p", hl.dsp.exec_cmd("setsid -f sh -c 'pkill wlogout || wlogout' >/dev/null 2>&1"), "Power menu")
bind(M .. " + CTRL + l", hl.dsp.exec_cmd("sys-power lock"), "Lock screen")
bind(M .. " + SHIFT + w", hl.dsp.exec_cmd("setsid -f customize wallpaper random >/dev/null 2>&1"), "Random wallpaper")
bind(M .. " + CTRL + w", hl.dsp.exec_cmd("setsid -f customize wallpaper >/dev/null 2>&1"), "Wallpaper selector")
bind(M .. " + ALT + g", hl.dsp.exec_cmd("nk-gamemode"), "Toggle game mode")
bind(M .. " + SHIFT + h", hl.dsp.exec_cmd("sunset-toggle"), "Toggle Hyprsunset")
bind(M .. " + SHIFT + b", hl.dsp.exec_cmd("change-navbar-mode"), "Change navbar mode")
bind(M .. " + CTRL + b", hl.dsp.exec_cmd("if ! pidof -q navbar-watcher && ! pidof -q navbar-hover; then pkill -SIGUSR1 waybar; fi"), "Toggle navbar")
bind(M .. " + w", hl.dsp.exec_cmd("setsid -f customize >/dev/null 2>&1"), "Customize desktop")

-- Special workspace / scratchpad.
bind(M .. " + s", hl.dsp.workspace.toggle_special("scratchpad"), "Toggle scratchpad")
bind(M .. " + SHIFT + s", hl.dsp.window.move({ workspace = "special:scratchpad" }), "Move window to scratchpad")

-- Media and hardware keys. These remain active while the screen is locked.
bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), "Raise volume", { locked = true, repeating = true })
bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), "Lower volume", { locked = true, repeating = true })
bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), "Mute audio", { locked = true })
bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), "Mute microphone", { locked = true })
bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"), "Increase brightness", { locked = true, repeating = true })
bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"), "Decrease brightness", { locked = true, repeating = true })
bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), "Next track", { locked = true })
bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), "Play/pause", { locked = true })
bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), "Play/pause", { locked = true })
bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), "Previous track", { locked = true })

-- Startup -------------------------------------------------------------------
hl.on("hyprland.start", function()
    local commands = {
        "dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP HYPRLAND_INSTANCE_SIGNATURE",
        "systemctl --user restart xdg-desktop-portal-hyprland xdg-desktop-portal",
        "wl-paste --type text --watch cliphist store",
        "wl-paste --type image --watch cliphist store",
        "hyprpolkitagent",
        "hypridle",
        "start-navbar",
        "hyprsunset",
        "swaync",
        "nm-applet --indicator",
        "hypr-nice",
        "awww-daemon",
        "sleep 1 && awww restore || true",
        "bash ~/.config/hypr/scripts/wallpapers/check-video.sh",
    }

    for _, command in ipairs(commands) do
        run(command)
    end
end)

-- Active NKS window skin. customize windows writes this state file and reloads Hyprland.
local skin_name = "legacy"
local skin_state = HOME .. "/.cache/nekoroshell/window_skin"
local sf = io.open(skin_state, "r")
if sf then
    local value = sf:read("*l")
    sf:close()
    if value and value:match("^[%w_-]+$") then
        local candidate = HOME .. "/.config/hypr/nks-window-skins/" .. value .. ".lua"
        local cf = io.open(candidate, "r")
        if cf then
            cf:close()
            skin_name = value
        end
    end
end
local skin_file = HOME .. "/.config/hypr/nks-window-skins/" .. skin_name .. ".lua"
local sf2 = io.open(skin_file, "r")
if sf2 then
    sf2:close()
    dofile(skin_file)
end

-- Personal override file. Users can add their own Lua without modifying this
-- main configuration.
local custom = HOME .. "/.config/hypr/custom.lua"
local f = io.open(custom, "r")
if f then
    f:close()
    dofile(custom)
end
